fix(#424): add stricter removing of unsupported JS names.
Kotlin/dukat pull request #450
Opened 2021-08-27 13:43 UTC by JSMonk

Change the logic of `getter/setters` creation from unsupported JS names for cases like this:
```ts
export interface A {
  'test@field: string;
}
```
```kotlin
// Previously compiled into: 
external interface A {
    var  test@field: String
}

// Currently compiled into:
external interface A {
    @nativeGetter
    operator fun get(key: String): String?
    @nativeSetter
    operator fun set(key: String, value: String)
}
```

### Questions to answer
1. I find that we have this removal logic only for interfaces here: https://github.com/Kotlin/dukat/blob/0263d1d1ed0b536f998c720d0c914bc0a3c01f84/model-lowerings/src/org/jetbrains/dukat/commonLowerings/removeUnsupportedJsNames.kt#L81 . Seems like we need the same logic for object and class types. Do we need to implement it?

2021-09-01 15:40 UTC, ilgonmic requested changes

2021-09-01 15:48 UTC, ilgonmic approved these changes

2021-09-01 17:12 UTC, JSMonk commented on compiler/test/data/typescript/node_modules/escaping/escaping.d.kt
> +    operator fun set(key: String, value: Number)
It makes sense. Will check.

2021-09-02 09:57 UTC, JSMonk commented on compiler/test/data/typescript/node_modules/escaping/escaping.d.kt
> +    operator fun set(key: String, value: Number)
Seems like the same behavior was presented before too:
https://github.com/Kotlin/dukat/blob/3862877c370b4a268c13f0b0d887292b1e680338/compiler/test/data/typescript/node_modules/escaping/escaping.d.kt#L37
https://github.com/Kotlin/dukat/blob/3862877c370b4a268c13f0b0d887292b1e680338/compiler/test/data/typescript/node_modules/escaping/escaping.d.kt#L39

2021-09-02 10:00 UTC, JSMonk commented on compiler/test/data/typescript/node_modules/escaping/escaping.d.kt
> +    operator fun set(key: String, value: Number)
Seems like the same behavior was presented before here:
https://github.com/Kotlin/dukat/blob/3862877c370b4a268c13f0b0d887292b1e680338/compiler/test/data/typescript/node_modules/escaping/escaping.d.kt#L39
https://github.com/Kotlin/dukat/blob/3862877c370b4a268c13f0b0d887292b1e680338/compiler/test/data/typescript/node_modules/escaping/escaping.d.kt#L37

2021-09-02 10:28 UTC, merged